### ISSUE TITLE
微信朋友圈的赞现在是显示昵称了,不是头像

### ISSUE THREAD

**Issue by Ctrlsman** [YulRW/WeChat-demo#1]

**Comment by Ctrlsman** [comment]
弄错了,详情页进去确实是头像

**Comment by YulRW** [comment]
收到。
恩，之后我确实会继续做一个pyq主页面，以后两者都会有的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Ctrlsman"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月17日(星期五) 下午4:38
收件人:&nbsp;"YulRW/WeChat-demo"<WeChat-demo@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [YulRW/WeChat-demo] 微信朋友圈的赞现在是显示昵称了,不是头像 (#1)





 
弄错了,详情页进去确实是头像
